apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-java-springboot-basic-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-java-springboot-basic-1
    app.kubernetes.io/part-of: devfile-sample-java-springboot-basic-1
  name: devfile-sample-java-springboot-basic-1
spec:
  ports:
  - name: http-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: java-springboot-app
    app.kubernetes.io/instance: devfile-sample-java-springboot-basic-1
status:
  loadBalancer: {}
